In [ ]:
from augment.augment import *
from augment.augment import Sigmoid
from augment.augment import AugmentNetwork

In [ ]:
p1 = Sigmoid(2)
print(p1.theta)

In [ ]:
#print all attributes and default settings of AugmentNetwork
p2 = AugmentNetwork();
attrs = vars(p2);
#print(', '.join("%s: %s" % item for item in attrs.items()))

In [ ]:
#all atributes in AugmentNetwork
dir(p2);

In [ ]:
python runner.py

In [ ]:
python runner

In [ ]:
%run runner

In [ ]:
tic()
%run runner
toc()

In [ ]:
pwd

In [ ]:
pwd

In [ ]:
from task import GGSA

In [ ]:
from augment.augment import AugmentNetwork

In [ ]:
from task.task import GGSA

In [ ]:
from tictoc import *

In [ ]:
tic()
toc()

In [1]:
import os
os.getcwd()
os.chdir("C:\\Users\\Lieke\\Documents\\4_CWI-NIN\\WM\\workmate-master")

In [ ]:
tic()
%run runner.run_dms()
toc()

In [ ]:
import string
print(string.ascii_uppercase)

In [ ]:
np.random.choice(list(string.ascii_uppercase))

In [ ]:
stims = np.random.choice(list(string.ascii_uppercase), 
            n_stim * (n_switches + 1), replace=False)
print(stims)

In [ ]:
n_stim = 3
n_switches = 2

In [ ]:
import w_runner
w_runner.run_dms()
#w_runner.run_otax()
#w_runner.run_ggsa(prefixed_gates = True)

In [ ]:
#using dpcstrings
print(w_runner.run_otax.__doc__)
help(w_runner.run_otax)

In [ ]:
os._exit(00)

In [ ]:
import numpy as np
import random
b = random.random()
print(b)
print(np.ones((4,5)))
a = np.mean(np.ones((4,5)),axis=1)
print(4-a)

In [ ]:
x = 10
y = 20
corr = (x >= y)
print(corr)

In [ ]:
import numpy as np
import string

##################### time cell coding #####################
maxtime  = 10
# Time vectors are created by convolving a response vector 
# with an identity matrix, yielding [maxtime] rows of time cell responses,
# each peaking at a unique, consecutive time.
z = [0.1, 0.25, 0.5, 1, 0.5, 0.25, 0.1]
# the '3'-cropping here removes edge artefacts from convolution; 
# Time cell 0 (at row 0) peaks at the first moment in time (column 0).
tmat = np.vstack([np.convolve(z, t) for t in np.eye(maxtime)])
print(tmat)

In [ ]:
for t in np.eye(maxtime)
    np.convolve(z, t)[ 3:t.size + 3] 
    print(t.sie)

In [ ]:
for t in np.eye(maxtime):
    print(t.size)

In [ ]:
maxtime  = 10
# Time vectors are created by convolving a response vector 
# with an identity matrix, yielding [maxtime] rows of time cell responses,
# each peaking at a unique, consecutive time.
z = [0.1, 0.25, 0.5, 1, 0.5, 0.25, 0.1]
# the '3'-cropping here removes edge artefacts from convolution; 
# Time cell 0 (at row 0) peaks at the first moment in time (column 0).
tmat = np.vstack([np.convolve(z, t)[ 3:t.size + 3] for t in np.eye(maxtime)])
print(tmat)

In [ ]:
print(len(z))

In [ ]:
crop = (len(z)-1)/2 
print(crop)

In [ ]:
print(len(maxtime))

In [ ]:
##################### time cell coding #####################
maxtime  = 10
# Time vectors are created by convolving a response vector 
# with an identity matrix, yielding [maxtime] rows of time cell responses,
# each peaking at a unique, consecutive time.
z = [0.1, 0.25, 0.5, 1, 0.5, 0.25, 0.1]
crop = int((len(z)-1)/2) # the '3'-cropping here removes edge artefacts from convolution; 
# Time cell 0 (at row 0) peaks at the first moment in time (column 0).
tmat = np.vstack([np.convolve(z, t)[crop:maxtime + crop] for t in np.eye(maxtime)])
print(tmat)

In [ ]:
print(crop)

In [ ]:
type(int(crop))

In [ ]:
stimbits = 7
binstr = '0{}b'.format(stimbits)
print(binstr)

In [ ]:
binstrings = [format(i, binstr) for i in range(2**stimbits)]
print(binstrings)
len(binstrings)

In [ ]:
2**7

In [ ]:
tobinarr = lambda s : np.array([float(c) for c in s])
print(tobinarr(binstrings[0]))

In [ ]:
Dx = np.vstack(  [tobinarr(i) for i in binstrings]  )
print(Dx)

In [ ]:
2**6

In [ ]:
chars = string.ascii_lowercase + string.ascii_uppercase
stimdict = dict( list(zip( chars, Dx )) )
print(stimdict)

In [ ]:
stimbits = 6 # (= (256 unique stimuli)) >> 128? (LJC)
# construct binary stim_repres
binstr = '0{}b'.format(stimbits)
binstrings = [format(i, binstr) for i in range(2**stimbits)]
tobinarr = lambda s : np.array([float(c) for c in s])
Dx = np.vstack(  [tobinarr(i) for i in binstrings]  )

# Dx now is a matrix of 128 x 7 bits. 'stimbits' is a dict that will order the 
# first 52 of these in a lookup table, #why not choose 2**6 when you only use the first 52? (LJC)
chars = string.ascii_lowercase + string.ascii_uppercase
stimdict = dict( list(zip( chars, Dx )) )
print(stimdict)

In [ ]:
stimdict['g'] = np.zeros(stimbits)
stimdict['p'] = np.eye(stimbits)[0]
stimdict['a'] = np.eye(stimbits)[1]
stimdict['l'] = np.eye(stimbits)[2]
stimdict['r'] = np.eye(stimbits)[3]

In [ ]:
print(stimdict['g'])

In [ ]:
digdict = dict( 
    [(d,Dx[i + 2**(stimbits-1) ]) for i,d in enumerate(string.digits) ])
stimdict.update( digdict )
print(digdict)
print(stimdict)

In [ ]:
import string
print(enumerate(string.digits))

In [ ]:
A = dict( 
    [(d,Dx[i + 2**(stimbits-1) ]) for ind,val in enumerate(string.digits) ])
print(A)

In [ ]:
Dx[0 + 2**(stimbits-1)]

In [ ]:
Dx[0]

In [ ]:
2**(stimbits-1)

In [ ]:
Dx[32]

In [ ]:
(1,Dx[0 + 2**(stimbits-1) ])

In [ ]:
for ind,val in enumerate(string.digits):
    print(ind)
    print(val)

In [ ]:
def get_obs(obs='A', t=0):
    # return time-stim vec:
    return np.r_[ tmat[t], stimdict[obs] ]
get_obs('B', 3)

In [ ]:
trial_type = np.random.choice([0,1])
tr = trial_type * 2
print(trial_type, tr)

In [ ]:
sample, probe = np.random.choice([1,2,3,34,4,5,6,7], 2, replace=False)
print(sample, probe)

In [ ]:
DMS.stimset

In [ ]:
env = DMS()
getattr(env,stimset)

In [ ]:
list("p{}p{}".format("A", "B") )

In [ ]:
import tasks
tasks.DMS().stimset
tasks.DMS().seq
print(len(tasks.DMS().seq))

In [ ]:
t = 2
seq = tasks.DMS().seq

def go():
# is is the end of the sequence?
    if t < len(seq):
        return 'RESET', 0.0
        print(t, len(seq))

go()

In [ ]:
import tasks
env = tasks.DMS()
x1 = tasks.Manual_agent(env)
x1.step()

In [3]:
import numpy as np
nx = 4;
nS = 3;
print(np.random.sample((nS, nx)))

[[0.77845902 0.9992492  0.62952706 0.27495495]
 [0.68694279 0.91928482 0.54095512 0.38705057]
 [0.285457   0.57302033 0.29042485 0.57114707]]


In [6]:
import w_runner
w_runner.run_dms()
#w_runner.run_otax()
#w_runner.run_ggsa(prefixed_gates = True)

300 	 0.008
600 	 0.052
900 	 0.136
1200 	 0.228
1500 	 0.324
1800 	 0.412
2100 	 0.436
2400 	 0.408
2700 	 0.368
3000 	 0.478
3300 	 0.498
3600 	 0.552
3900 	 0.54
4200 	 0.59
4500 	 0.626
Convergence at 4757	Switch to set 1
4800 	 0.046
5100 	 0.406
Convergence at 5185	Switch to set 2
5400 	 0.244
5700 	 0.554
6000 	 0.646
Convergence at 6087	Switch to set 3
6300 	 0.312
Convergence at 6312	Switch to set 4
6600 	 0.428
Convergence at 6685	Switch to set 5
Convergence at 6819	Switch to set 6


(array([4757., 5185., 6087., 6312., 6685., 6819.]),
 array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  1.,  1., ..., nan, nan, nan],
        [ 1.,  0.,  0., ...,  0.,  1.,  1.],
        [ 0.,  1.,  1., ..., nan, nan, nan],
        [ 0.,  1.,  1., ..., nan, nan, nan],
        [ 0.,  1.,  1., ..., nan, nan, nan]]))

In [3]:
import w_runner
w_runner.run_dms()
#w_runner.run_otax()
#w_runner.run_ggsa(prefixed_gates = True)

300 	 0.008
600 	 0.052
900 	 0.136
1200 	 0.228
1500 	 0.324
1800 	 0.412
2100 	 0.436
2400 	 0.408
2700 	 0.368
3000 	 0.478
3300 	 0.498
3600 	 0.552
3900 	 0.54
4200 	 0.59
4500 	 0.626
Convergence at 4757	Switch to set 1
4800 	 0.046
5100 	 0.406
Convergence at 5185	Switch to set 2
5400 	 0.244
5700 	 0.554
6000 	 0.646
Convergence at 6087	Switch to set 3
6300 	 0.312
Convergence at 6312	Switch to set 4
6600 	 0.428
Convergence at 6685	Switch to set 5
Convergence at 6819	Switch to set 6


(array([4757., 5185., 6087., 6312., 6685., 6819.]),
 array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  1.,  1., ..., nan, nan, nan],
        [ 1.,  0.,  0., ...,  0.,  1.,  1.],
        [ 0.,  1.,  1., ..., nan, nan, nan],
        [ 0.,  1.,  1., ..., nan, nan, nan],
        [ 0.,  1.,  1., ..., nan, nan, nan]]))

In [4]:
import control

ModuleNotFoundError: No module named 'control'

In [5]:
import numpy

In [8]:
!pip install control

  Using cached https://files.pythonhosted.org/packages/e8/b0/32a903138505dd4ea523f8a3fc156c4272aa58b10100ef24ff74ced2fae8/control-0.8.3.tar.gz
  Stored in directory: C:\Users\Lieke\AppData\Local\pip\Cache\wheels\c2\d9\cc\90b28cb139a6320a3af2285428b6da87eee8d8920c78bb0223
Successfully built control


In [9]:
import control

In [10]:
import sys
!{sys.executable} -m pip install control